# The test environment docker compose creates the following services in a single network:
#
# - solana validator where it's the only node in the cluster.

#
# Individual integration tests are meant to spin up their own instance of the docker compose cluster,
# using unique project names and unused port numbers to avoid conflicts so that multiple tests can run concurrently. -> check on the TPG repo
#
# Tests can then make http requests to the following ports mapped on localhost:
# - ${SOLANA_RPC_PORT}: the validator's solana json rpc
services:
  validator:
    container_name: solana-validator
    image: docker.io/lifeofpavs/solana-test-validator:latest
    command: [
        "solana-test-validator",                      # Reset flag
        "--reset",
        "-w", "332507309",
        "--account-dir", "/test-fixtures", # payer, staker authority
        "--clone-upgradeable-program", "SP12tWFxD9oJsVWNavTTBZvMbA6gkAmxtVgxdqvyvhY", # sanctum single validator stake-pool programSPMBzsVUuoHA4Jm6KunbsotaahvVikZs1JyTW6iJvbn
        "--clone-upgradeable-program", "SPMBzsVUuoHA4Jm6KunbsotaahvVikZs1JyTW6iJvbn", # sanctum multiple validator stake-pool program
        "--clone-upgradeable-program", "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy", # stake pool program
        "--clone-upgradeable-program", "unpXTU2Ndrc7WWNyEhQWe4udTzSibLPi25SXv2xbCHQ", # sanctum unstake program
        "--clone-upgradeable-program", "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD", # marinade staking program
        "--deactivate-feature", "9onWzzvCzNC2jfhxxeqRgs5q7nFAAKpCUvkj6T6GJK9i", # deactivate 1 SOL minimum delegation stake
        "-um"
    ]
    volumes:
      - ./test-fixtures:/test-fixtures
    ports:
      - "8899:8899" # http rpc
      - "8900:8900" # websocket rpc